kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: edge-inference
  namespace: fleet-default
spec:
  repo: ssh://git@git-ssh.atoy.lol/home/edge-inference.git
  clientSecretName: private-key
  branch: main
  targets:
  - name: inference
    clusterSelector:
      matchLabels:
        inference: enabled
  paths:
  - ./helm