{{- if and (.Values.deepstack.enabled) ().Values.deepstack.persistence.enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepstack-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.deepstack.persistence.size }}
  storageClassName: {{ .Values.deepstack.persistence.storageClass }}
{{- end }}