apiVersion: v1
kind: Service
metadata:
  name: rtsp
  labels:
    app: rtsp
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.rtsp.port }}
      targetPort: udp
      protocol: TCP
      name: udp
  selector:
    app: rtsp
