apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffmpeg
  labels:
    app: ffmpeg
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ffmpeg
  template:
    metadata:
      labels:
        app: ffmpeg
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ffmpeg.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.ffmpeg.podSecurityContext | nindent 8 }}
      containers:
        - name: ffmpeg
          resources:
            limits:
              akri.sh/akri-logitech: "1"
          image: "{{ .Values.ffmpeg.image }}:{{ .Values.ffmpeg.tag }}"
          imagePullPolicy: {{ .Values.ffmpeg.pullPolicy }}
          volumeMounts:
          - mountPath: /dev/video0
            name: dev-video0
          securityContext:
            privileged: true
          command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash

              ffmpeg -f video4linux2 -an -i /dev/video0 -b:v 1500k -r 30 -maxrate 2000k -minrate 1000k -bufsize 500k -tune zerolatency -preset veryfast -c:v libx264 -f rtsp -rtsp_transport tcp rtsp://rtsp.{{ .Release.Namespace }}.svc.cluster.local:8554/cam
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0