deepstack:
  enabled: false
  ingress:
    hosts:
    - host: deepstack.ai.atoy.lol
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
    - hosts:
      - deepstack.ai.atoy.lol
      secretName: ai-cert
  persistence:
    enabled: true
doubleTake:
  ingress:
    hosts:
    - host: double-take.ai.atoy.lol
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
    - hosts:
      - double-take.ai.atoy.lol
      secretName: ai-cert
frigate:
  ingress:
    hosts:
    - host: frigate.ai.atoy.lol
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
    - hosts:
      - frigate.ai.atoy.lol
      secretName: ai-cert
  persistence:
    enabled: true
  record: false
  snapshots: true
  detectors:
    coral:
      type: edgetpu
      device: usb
      model:
        path: "/models/ssdlite_mobiledet_coco_qat_postprocess_edgetpu.tflite"
  objects:
  - person
  - banana
  - umbrella
  - hot dog
  - person
  - bicycle
  - car
  - motorcycle
  - airplane
  - bus
  - train
  - truck
  - boat
  - traffic light
  - fire hydrant
  - stop sign
  - parking meter
  - bench
  - bird
  - cat
  - dog
  - horse
  - sheep
  - cow
  - elephant
  - bear
  - zebra
  - giraffe
  - backpack
  - umbrella
  - handbag
  - tie
  - suitcase
  - frisbee
  - skis
  - snowboard
  - sports ball
  - kite
  - baseball bat
  - baseball glove
  - skateboard
  - surfboard
  - tennis racket
  - bottle
  - wine glass
  - cup
  - fork
  - knife
  - spoon
  - bowl
  - banana
  - apple
  - sandwich
  - orange
  - broccoli
  - carrot
  - hot dog
  - pizza
  - donut
  - cake
  - chair
  - couch
  - potted plant
  - bed
  - dining table
  - toilet
  - tv
  - laptop
  - mouse
  - remote
  - keyboard
  - cell phone
  - microwave
  - oven
  - toaster
  - sink
  - refrigerator
  - book
  # - clock
  # - vase
  # - scissors
  # - teddy bear
  # - hair drier
  # - toothbrush

  filters:
    person:
      threshold: 0.6

  customModels:
  - https://raw.githubusercontent.com/google-coral/test_data/master/ssdlite_mobiledet_coco_qat_postprocess_edgetpu.tflite
