deepstack:
  enabled: false
  ingress:
    hosts:
    - host: deepstack.ai.atoy.lol
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
    - hosts:
      - deepstack.ai.atoy.lol
      secretName: ai-cert
  persistence:
    enabled: true
doubleTake:
  ingress:
    hosts:
    - host: double-take.ai.atoy.lol
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
    - hosts:
      - double-take.ai.atoy.lol
      secretName: ai-cert
frigate:
  ingress:
    hosts:
    - host: frigate.ai.atoy.lol
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
    - hosts:
      - frigate.ai.atoy.lol
      secretName: ai-cert
  persistence:
    enabled: true
  detectors:
    coral:
      type: edgetpu
      device: usb
      model:
        path: "/models/tf2_ssd_mobilenet_v1_fpn_640x640_coco17_ptq_edgetpu.tflite"
  customModels:
  - https://raw.githubusercontent.com/google-coral/test_data/master/tf2_ssd_mobilenet_v1_fpn_640x640_coco17_ptq_edgetpu.tflite