apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
data:
  config.yml: |
    mqtt:
      {{- if .Values.mqtt.enabled }}
      enabled: True
      host: mqtt.{{ .Release.Namespace }}.svc.cluster.local
      port: {{ .Values.mqtt.mqttPort }}
      user: {{ .Values.mqtt.auth.username }}
      password: {{ .Values.mqtt.auth.password }}
      {{- else }}
      enabled: False
      {{- end }}
    detectors:
    {{- with .Values.frigate.detectors }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    cameras:
      main:
        mqtt:
          timestamp: False
          bounding_box: False
          crop: True
          quality: 100
          height: 500
        ffmpeg:
          inputs:
            - path: rtsp://rtsp.{{ .Release.Namespace }}.svc.cluster.local:8554/cam
              roles:
                - detect
        detect:
          width: 1280
          height: 720