apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
data:
  config.yml: |
    mqtt:
      {{- if .Values.mqtt.enabled }}
      enabled: True
      host: mqtt.{{ .Release.Namespace }}.svc.cluster.local
      port: {{ .Values.mqtt.mqttPort }}
      user: {{ .Values.mqtt.auth.username }}
      password: {{ .Values.mqtt.auth.password }}
      {{- else }}
      enabled: False
      {{- end }}
    detectors:
    {{- with .Values.frigate.detectors }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if .Values.frigate.snapshots }}
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 5
      quality: 70
    {{- end }}
    {{- if .Values.frigate.record }}
    record:
      enabled: True
      events:
        pre_capture: 2
        post_capture: 2
        retain:
          default: 1
    {{- end }}
    cameras:
      main:
        enabled: True
        mqtt:
          timestamp: False
          bounding_box: False
          crop: True
          quality: 100
          height: 500
        ffmpeg:
          inputs:
            - path: rtsp://rtsp.{{ .Release.Namespace }}.svc.cluster.local:8554/cam
              roles:
                - detect
                - record
            - path: rtsps://10.0.10.190:7441/kDuGZVjvs7cPYxcS?enableSrtp
              roles:
                - detect
                - record
    {{- with .Values.frigate.objects }}
    objects:
      track:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.frigate.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
    {{- end }}