apiVersion: v1
kind: Service
metadata:
  name: frigate
  labels:
    app: frigate
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frigate.rtspPort }}
      targetPort: rtsp
      protocol: TCP
      name: rtsp
    - port: {{ .Values.frigate.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: frigate
