{{- if .Values.mqtt.enabled }}
{{-  $mqttCreds := printf "%s:%s" .Values.mqtt.auth.username .Values.mqtt.auth.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: mqtt-secret
data:
  MQTT_USER: {{ .Values.mqtt.auth.username | b64enc }}
  MQTT_PASSWORD: {{ .Values.mqtt.auth.password | b64enc }}
{{- end }}